### ISSUE TITLE
X failed to start

### ISSUE THREAD

**Issue by kitlaan** [pureartisan/magic-mirror-raspbian-lite#5]
FYI, with a brand new install of bookworm lite, Xorg failed to start (with tty and "virtual console" errors).

I had to add `~/.xserverrc` with contents:

```bash
#!/bin/sh

exec /usr/bin/X -nolisten tcp "$@" vt${XDG_VTNR}
```

**Comment by prageeth** [comment]
@kitlaan PRs are welcome :)

**Comment by kitlaan** [comment]
:+1:

curious if anyone else has run into this, or am I just the first to use your script & bookworm :grin:

**Comment by markusand** [comment]
I also have problems starting xserver with Bullseye
